### ISSUE TITLE
Reduce load on airtable by archiving old people/nominations

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/hub#15]

**Comment by ben-pr-p** [comment]
Fixed by https://github.com/BrandNewCongress/hub/pull/22.

I ran the script with queries to match People and Evaluations I should delete and in total deleted around 8,000 records. Should be good for now?

**Comment by ben-pr-p** [comment]
I've scheduled backups now at 11 AM UTC (6AM EST) (3 AM CT), when I figured people would be least likely to use Airtable as the back up script may slow down the GUI, etc.
