### ISSUE TITLE
Consider switching from eslint to prettier

### ISSUE THREAD

**Issue by traviskaufman** [BrandNewCongress/hub#23]
https://github.com/prettier/prettier

Checked out this repo and ran `npm run lint` and noticed a bunch of errors. Prettier is really useful for this because you can auto-format all of your code before each commit/PR and never have to worry about lint / style errors.

**Comment by ben-pr-p** [comment]
I'll be working on writing tests and zero linting errors soon, but I think `eslint . --fix` should be enough for that

**Comment by ben-pr-p** [comment]
Thanks for the suggestion, I'm going to use prettier-eslint (I know the point is no opinions but I still don't like semi-colons)
